apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/a3156474-eead-4d25-ad9d-952bb6f94ed7/resourcegroups/ICSyndicate/providers/Microsoft.Compute/disks/Grafana-stg
