apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/fe7c10b4-bc92-4498-ae84-adf993d6cc1d/resourcegroups/ICSyndicateProd/providers/Microsoft.Compute/disks/grafana-prod
