apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: logging
  labels:
    data: grafana-ui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana
  volumeMode: Filesystem
  volumeName: pv-prometheus
  resources:
    requests:
      storage: 16Gi  