apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  labels:
    data: grafana-ui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana
  volumeMode: Filesystem
  volumeName: pv-grafana
  resources:
    requests:
      storage: 8Gi